### ISSUE TITLE
Not Able to Read Health Step Count Data Without open Health App

### ISSUE THREAD

**Issue by rajaiogames** [kilohealth/rn-fitness-tracker#56] opened 2021-08-06 12:31 UTC
I am using this plugins then getting the issue when Health application not launch and want to get the step count then not able to get step count, but when I open the Health app then it's reading perfactaly,

So can you help me how can read the step count data without open Health app

Anyware we have to put the code for active and read the Health app step data, It may some code we have to put in AppDelegate file.

Please suggest me. please help for this issue

**Comment by lukebars** [comment] 2022-07-27 14:39
Hello @rajaiogames, sorry for really late reply, we haven't been able to reproduce your issue back in the day, but maybe you remember what was the exact issue? Was the HealthTrackerAPI not working when Health app was closed or when Health app was not opened for the first time since setting up the iPhone?

**Comment by lukebars** [comment] 2022-07-28 13:43
Closing this, as no reproduction was provided

**Closed by lukebars** 2022-07-28 13:43 UTC
